/******************************************
Christine Treacy
Random Quote Generator (project 1)
******************************************/

var quotes;
var colors;
var randomNum;
var randomQ;
var stringHTML;

//background colors array
colors = ['#004d99','#0066cc','#0080ff','#3399ff','#66b3ff','#99ccff','#003366','#1a75ff','#4d94ff'];

//quotes array of objects
quotes = [
  {
    quote: "I remember when the candle shop burned down. Everyone stood around singing 'Happy Birthday'.", 
    source: "Steven Wright"
  },
  {
    quote: "Take your risks now, as you grow older you become more fearful and less flexible. And I mean that literally. I hurt my knee this week on the treadmill, and it wasn’t even on.", 
    source: "Amy Poehler"
  },
  {
    quote: "Mother Teresa didn’t walk around complaining about her thighs – she had shit to do.", 
    source: "Sarah Silverman"    
  },
  {
    quote: "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.",
    source: "Jane Austen",
    citation: "Pride and Prejudice", 
    year: 1813
  },
  {
    quote: "This life’s hard, but it’s harder if you’re stupid.",
    source: "George V. Higgins",
    citation: "The Friends of Eddie Coyle"
  },
  {
    quote: "It’s my belief we developed language because of our deep inner need to complain.", 
    source:"Lily Tomlin"
  },
  {
    quote: "Most people work just hard enough not to get fired and get paid just enough money not to quit.", 
    source: "George Carlin"
  },
  {
    quote: "When you have bacon in your mouth, it doesn’t matter who’s president.", 
    source: "Louis C. K."
  },
  {
    quote: "I love deadlines. I love the whooshing noise they make as they go by.",
    source: "Douglas Adams", 
    citation: "The Salmon of Doubt",
    year: 2002
  }
];


function getRandomQuote(){
  randomNum = Math.floor(Math.random() * 8); //generate random number between 0 and 8
  return quotes[randomNum]; //return quote at index generated by randomNum
};

function getRandomColor(){
  randomColor = Math.floor(Math.random() * 8); //generate random color between 0 and 8
  return colors[randomColor]; //return color at index generated by randomColor
};


/***
  Create the `printQuote` function to: 
   - Call the `getRandomQuote` function and assign it to a variable.
   - Create a variable for the HTML string and set it equal to an empty string.
   - Use the HTML template in the instructions or the markup in the index.html file, AND 
     the random quote vairable to build your HTML string.
   - Add the quote and source section to the HTML string.
   - Use an if statement to check for the citation property before adding it to the HTML string.
   - Use an if statement to check for the year property before adding it to the HTML string.
   - Don't forget to close that final `p` tag.
   - Set the `innerHTML` of the `quote-box` div to the HTML string. 
***/

function printQuote(){
  randomQ = getRandomQuote();
  stringHTML = " ";
  stringHTML += '<p class="quote">';
  stringHTML += randomQ.quote + '</p>';
  stringHTML += '<p class="source">';
  stringHTML += randomQ.source;
  if (randomQ.citation!=undefined){ //check for not empty citation
    stringHTML += '<span class="citation">'; 
    stringHTML += randomQ.citation + '</span>';
  }
  if (randomQ.year!=undefined){ //check for not empty year
    stringHTML += '<span class="year">';
    stringHTML += randomQ.year + '</span>';
  }
  stringHTML+= '</p>';
  document.getElementById("quote-box").innerHTML = stringHTML;
  document.body.style.backgroundColor = getRandomColor();
};


document.getElementById('loadQuote').addEventListener("click", printQuote, false);


// Remember to delete the comments that came with this file, and replace them with your own code comments.