/******************************************
Christine Treacy
Random Quote Generator (project 1)
--Tested in Chrome, Edge and IE--
******************************************/

let randomNum;
let randomQ;
let stringHTML;
const button = document.getElementById('loadQuote');

//background colors array
const colors = ['#004d99','#0066cc','#0080ff','#3399ff','#66b3ff','#1a8cff','#003366','#1a75ff','#4d94ff'];

//quotes array of objects
const quotes = [
  {
    quote: "I remember when the candle shop burned down. Everyone stood around singing 'Happy Birthday'.", 
    source: "Steven Wright"
  },
  {
    quote: "Take your risks now, as you grow older you become more fearful and less flexible. And I mean that literally. I hurt my knee this week on the treadmill, and it wasn’t even on.", 
    source: "Amy Poehler",
    person: "comedian/actress"
  },
  {
    quote: "Mother Teresa didn’t walk around complaining about her thighs – she had shit to do.", 
    source: "Sarah Silverman",
    person: "comedian/actress"    
  },
  {
    quote: "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.",
    source: "Jane Austen",
    person: "author",
    citation: "Pride and Prejudice", 
    year: 1813
  },
  {
    quote: "This life’s hard, but it’s harder if you’re stupid.",
    source: "George V. Higgins",
    citation: "The Friends of Eddie Coyle"
  },
  {
    quote: "It’s my belief we developed language because of our deep inner need to complain.", 
    source: "Lily Tomlin",
    person: "actress"
  },
  {
    quote: "Most people work just hard enough not to get fired and get paid just enough money not to quit.", 
    source: "George Carlin",
    person: "comedian/actor"
  },
  {
    quote: "When you have bacon in your mouth, it doesn’t matter who’s president.", 
    source: "Louis C. K.",
    person: "comedian"
  },
  {
    quote: "I love deadlines. I love the whooshing noise they make as they go by.",
    source: "Douglas Adams", 
    person: "author",
    citation: "The Salmon of Doubt",
    year: 2002
  }
];

const getRandomQuote = () => {
  randomNum = Math.floor(Math.random() * 8); //generate random number between 0 and 8
  return quotes[randomNum]; //return quote at index generated by randomNum
};

const getRandomColor = () => {
  randomColor = Math.floor(Math.random() * 8); //generate random color between 0 and 8
  return colors[randomColor]; //return color at index generated by randomColor
};

const printQuote = () => { //create string of HTML
  clearInterval(myVar);
  randomQ = getRandomQuote();
  let currIndex = quotes.indexOf(randomQ)
  console.log(currIndex)
  let newIndex = getRandomQuote.findIndex;
  console.log(newIndex)
  if(currIndex = newIndex){}
  else {
    stringHTML = " ";
    stringHTML += '<p class="quote">' + randomQ.quote + '</p>' + '<p class="source">' + randomQ.source;
    if (randomQ.person){ //check if person property exists
      stringHTML += '<span class="person">' + randomQ.person + '</span>';
    }
    if (randomQ.citation){ //check if citation property exists
      stringHTML += '<span class="citation">' + randomQ.citation + '</span>';
    }
    if (randomQ.year){ //check if year property exists
      stringHTML += '<span class="year">' + randomQ.year + '</span>';
    }
    stringHTML+= '</p>';
    document.getElementById("quote-box").innerHTML = stringHTML;
    document.body.style.backgroundColor = getRandomColor(); //changes background color every time button is clicked
    button.style.backgroundColor = document.body.style.backgroundColor; //sets button color to background color
    myVar = setInterval(printQuote, 8000);
  }
};

var myVar = setInterval(printQuote, 8000);
button.addEventListener("click", printQuote, false);
 


