/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

// Study guide for this project - https://drive.google.com/file/d/1s5grutGuQFwJcQP8bFwEI69Q8FCkGdDk/view?usp=sharing
var quotes;
var randomNum;
var randomQ;
var stringHTML;

/*** 
  Create the array of quote objects and name it `quotes`.
  Add at least five quote objects to the `quotes` array.
  Give each quote object a `quote` and `source` property.
  Add the `citation` property to at least one object in the array.
  Add the `year` property to at least one object in the array.
  Use console.log() to log your array of quotes to the console.
***/

quotes = [
  {
    quote: "I remember when the candle shop burned down. Everyone stood around singing 'Happy Birthday'.", 
    source: "Steven Wright", 
    citation: "X Movie",
    year: 2007
  },
  {
    quote: "Take your risks now, as you grow older you become more fearful and less flexible. And I mean that literally. I hurt my knee this week on the treadmill, and it wasn’t even on.", 
    source: "Amy Poehler", 
  },
  {quote: "Mother Teresa didn’t walk around complaining about her thighs – she had shit to do.", source: "Sarah Silverman"},
  {quote: "It’s my belief we developed language because of our deep inner need to complain.", source:"Lily Tomlin"},
  {quote: "Most people work just hard enough not to get fired and get paid just enough money not to quit.", source: "George Carlin"},
  {quote: "When you have bacon in your mouth, it doesn’t matter who’s president.", source: "Louis C. K."}

];
console.log(quotes);


/***
  Create the `getRandomQuote` function to:
   - Create a variable to store a random number 
   - use the random number to `return` a random quote object from the `quotes` array.
***/

function getRandomQuote(){
  randomNum = Math.floor(Math.random() * 6); //generate random number between 0 and 5
  return quotes[randomNum]; //return quote at index generated by randomNum
};
console.log(getRandomQuote());

/***
  Create the `printQuote` function to: 
   - Call the `getRandomQuote` function and assign it to a variable.
   - Create a variable for the HTML string and set it equal to an empty string.
   - Use the HTML template in the instructions or the markup in the index.html file, AND 
     the random quote vairable to build your HTML string.
   - Add the quote and source section to the HTML string.
   - Use an if statement to check for the citation property before adding it to the HTML string.
   - Use an if statement to check for the year property before adding it to the HTML string.
   - Don't forget to close that final `p` tag.
   - Set the `innerHTML` of the `quote-box` div to the HTML string. 
***/

function printQuote(){
  randomQ = getRandomQuote();
  stringHTML = " ";
  stringHTML += "<p class='quote'>";
  stringHTML += randomQ.quote + "</p>";
  stringHTML += "<p class='source'>";
  stringHTML += randomQ.source;
  if (randomQ.citation!=' '){
    stringHTML += "<span class='citation'>"; //add commas after source and citation
    stringHTML += randomQ.citation + "</span>";
  } else if (randomQ.year=== true){
    stringHTML += "<span class='year'>";
    stringHTML += randomQ.year + "</span>";
  } else {
    stringHTML+= "</p>";
  }
  // return stringHTML;
  document.getElementById("quote-box").innerHTML = stringHTML;
};


/***
  When the "Show another quote" button is clicked, the event listener 
  below will be triggered, and it will call, or "invoke", the `printQuote` 
  function. So do not make any changes to the line of code below this 
  comment.
***/

document.getElementById('loadQuote').addEventListener("click", printQuote, false);


// Remember to delete the comments that came with this file, and replace them with your own code comments.